version: "3.3"

services:
  web:
    # The root directory from which we're building.
    build: .
    image: dachinat/whois_ge:latest

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"

    # Specify the values of the environment variables
    # used in this container.
    environment:
      RAILS_ENV: development

